### PR TITLE
PLAT-80070: Update CLI dependencies for Node 10

### PR DESCRIPTION
**Pull request by JayCanuck**
Node 6.x support ended long ago. Currently Node 8.x, 10.x, and 12.x are in LTS status, with 8.x in maintenance mode. See https://nodejs.org/en/about/releases/

Several dependencies have cut off support for old <8.x Node. Now is a good time to move forward, setting 8.10.0 as the new baseline as we adopt these dependency updates.

Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

### CODE REVIEW

**Comment by ryanjduffy** [comment]
Could we leapfrog 8 so we aren't "pushed" to update again sooner than necessary?

**Comment by JayCanuck** [comment]
We could jump to 10.x, but I'd rather now block out users artificially. 8.x is still supported until December, so there's still a decent time.  8.x seems like the same/general community norm at this point as I'd rather not jump the gun just yet. Just my personal opinion though.

**Comment by webOS101** [comment]
The `engines` property doesn't actually block anything, IIRC.  We could specify >= 10 and still work with 8 but just not guarantee it.  Is that correct?

**Comment by JayCanuck** [comment]
True, `engines` will not cause it to die, just warn. The idea, conceptually, is for `engines` to warn of incompatibilities with the software itself. To which currently, our only incompatibility is Node <8.10.0.

**Comment by JayCanuck** [comment]
One middleground could be to advocate optimal experience using 10.x or 12.x, but leave the hard incompatibility gatekeeping at 8.10.0

**Comment by JayCanuck** [comment]
Based on discussion, revised to target Node 10 LTS as baseline engine.

**Pull request merged**
