### PR TITLE
ENYO-5269: Relocate proptype-checker into mocha-react-proptype-checker

### PR DESCRIPTION
**Pull request by JayCanuck**
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

### CODE REVIEW

**Comment by ryanjduffy** [comment]
I think it makes more sense to make `proptype-checker` its own npm package (maybe as `mocha-react-proptype-checker` or something) which has a dependency upon `console-snoop`. They don't seem to be solving the same problems to be in the same package. WDYT?

**Comment by JayCanuck** [comment]
Feels a bit excessive to have an extra package on the chain.  Both felt very similar in purpose to me; capturing/handling proptype warnings/errors sent to the console via sinon.. To me, the proptype-checker was more of a feature that could be modularly included under the same banner (given the utility of this package) rather than a standalone package.  I'm open to making a `sinon-console-proptype-test` package if necessary, I'm not personally sold on the idea.

**Comment by ryanjduffy** [comment]
Consider it from the consumer's standpoint rather than the build standpoint. As a consumer of `proptype-checker`, is the means by which it checks for errors relevant to you? I'd argue that it isn't and you're only concerned that it checks and how it integrates (via `mocha` hooks).

**Comment by JayCanuck** [comment]
Fair enough points. I'll go ahead and whip up a repo/npm publish and update this PR 👍

**Comment by JayCanuck** [comment]
@ryanjduffy  updated :)

**Pull request merged**
